/*

 BLOCK_POINTER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __block_pointer_h_INCLUDE
#define __block_pointer_h_INCLUDE

/* Bank of tiles. */
#define block_pointerBank 0
/* Start of tile array. */
extern const unsigned char block_pointer[];

#endif

/* End of BLOCK_POINTER.H */
