/*

 F_MAP_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 15
   Tile set      : C:\Users\josem\Documents\Cuarto_Curso\TFG\github\proyecto_tfg\res\map_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __f_map_1_h_INCLUDE
#define __f_map_1_h_INCLUDE

#define f_map_1Width 20
#define f_map_1Height 15
#define f_map_1Bank 0

extern const unsigned char f_map_1[];
extern const unsigned char objects_f_map_1[];
extern const unsigned char blocks_f_map_1[];

#endif

/* End of F_MAP_1.H */
