/*

 F_MAP_2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 15
   Tile set      : C:\Users\josem\Documents\Cuarto_Curso\TFG\github\proyecto_tfg\res\map_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __f_map_2_h_INCLUDE
#define __f_map_2_h_INCLUDE

#define f_map_2Width 20
#define f_map_2Height 15
#define f_map_2Bank 0

extern const unsigned char f_map_2[];

#endif

/* End of F_MAP_2.H */
