/*

 FINAL_MESSAGE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\josem\Documents\Cuarto_Curso\TFG\github\proyecto_tfg\res\hud_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 96
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __final_message_h_INCLUDE
#define __final_message_h_INCLUDE

#define final_messageWidth 20
#define final_messageHeight 18
#define final_messageBank 0

extern const unsigned char final_message[];

#endif

/* End of FINAL_MESSAGE.H */
