/*

 GAME_OVER_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : map_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __game_over_screen_h_INCLUDE
#define __game_over_screen_h_INCLUDE

#define game_over_screenWidth 20
#define game_over_screenHeight 18
#define game_over_screenBank 0

extern const unsigned char game_over_screen[];

#endif

/* End of GAME_OVER_SCREEN.H */
