/*

 HUD_OPTIONS_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 16

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __hud_options_sprites_h_INCLUDE
#define __hud_options_sprites_h_INCLUDE

/* Bank of tiles. */
#define hud_options_spritesBank 0
/* Start of tile array. */
extern const unsigned char hud_options_sprites[];

#endif

/* End of HUD_OPTIONS_SPRITES.H */
