/*

 HUD_RUNNING.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : C:\Users\josem\Documents\Cuarto_Curso\TFG\github\proyecto_tfg\res\hud_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 96
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __HUD_running_h_INCLUDE
#define __HUD_running_h_INCLUDE

#define HUD_runningWidth 20
#define HUD_runningHeight 4
#define HUD_runningBank 0

extern const unsigned char HUD_running[];

#endif

/* End of HUD_RUNNING.H */
