/*

 HUD_SELECTOR.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : C:\Users\josem\Documents\Cuarto_Curso\TFG\github\proyecto_tfg\res\hud_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 44
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __hud_selector_h_INCLUDE
#define __hud_selector_h_INCLUDE

#define hud_selectorWidth 20
#define hud_selectorHeight 3
#define hud_selectorBank 0
#define hud_selectorTileOffset 44

extern const unsigned char hud_selector[];

#endif

/* End of HUD_SELECTOR.H */
