/*

 HUD_SELECTOR.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : hud_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 104
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __hud_selector_h_INCLUDE
#define __hud_selector_h_INCLUDE

#define hud_selectorWidth 20
#define hud_selectorHeight 4
#define hud_selectorBank 0

extern const unsigned char hud_selector[];

#endif

/* End of HUD_SELECTOR.H */
