/*

 MAP1_ALT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 15
   Tile set      : map_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map1_alt_h_INCLUDE
#define __map1_alt_h_INCLUDE

#define map1_altWidth 20
#define map1_altHeight 15
#define map1_altBank 0

extern const unsigned char map1_alt[];
extern const unsigned char objects_map1_alt[];
extern const unsigned char blocks_map1_alt[];

#endif

/* End of MAP1_ALT.H */
