/*

 MAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : map_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map1_h_INCLUDE
#define __map1_h_INCLUDE

#define map1Width 20
#define map1Height 18
#define map1Bank 0

extern const unsigned char map1[];
extern const unsigned char objects_map1[];
extern const unsigned char blocks_map1[];

#endif

/* End of MAP1.H */
