/*

 MAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 15
   Tile set      : map_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map2_h_INCLUDE
#define __map2_h_INCLUDE

#define map2Width 20
#define map2Height 15
#define map2Bank 0

extern const unsigned char map2[];
extern const unsigned char objects_map2[];
extern const unsigned char blocks_map2[];

#endif

/* End of MAP2.H */
