/*

 MAP_NEW_TILES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 16
   Tile set      : C:\Users\josem\Documents\Cuarto_Curso\TFG\github\proyecto_tfg\res\map_tiles - copia.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map_new_tiles_h_INCLUDE
#define __map_new_tiles_h_INCLUDE

#define map_new_tilesWidth 20
#define map_new_tilesHeight 16
#define map_new_tilesBank 0

extern const unsigned char map_new_tiles[];

#endif

/* End of MAP_NEW_TILES.H */
