/*

 MAP_TEST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 15
   Tile set      : map_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map_test_h_INCLUDE
#define __map_test_h_INCLUDE

#define map_testWidth 20
#define map_testHeight 15
#define map_testBank 0

extern const unsigned char map_test[];
extern const unsigned char objects_map_test[];
extern const unsigned char blocks_map_test[];


#endif

/* End of MAP_TEST.H */
