/*

 PAUSA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : C:\Users\josem\Documents\Cuarto_Curso\TFG\github\proyecto_tfg\res\hud_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 96
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __pausa_h_INCLUDE
#define __pausa_h_INCLUDE

#define pausaWidth 20
#define pausaHeight 12
#define pausaBank 0

extern const unsigned char pausa[];

#endif

/* End of PAUSA.H */
