//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_png_prueba_H
#define METASPRITE_png_prueba_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define png_prueba_TILE_ORIGIN 0
#define png_prueba_TILE_W 8
#define png_prueba_TILE_H 8
#define png_prueba_WIDTH 160
#define png_prueba_HEIGHT 144
#define png_prueba_TILE_COUNT 232
#define png_prueba_PALETTE_COUNT 1
#define png_prueba_COLORS_PER_PALETTE 4
#define png_prueba_TOTAL_COLORS 4
#define png_prueba_MAP_ATTRIBUTES 0
extern const unsigned char png_prueba_map[360];
#define png_prueba_map_attributes png_prueba_map

BANKREF_EXTERN(png_prueba)

extern const palette_color_t png_prueba_palettes[4];
extern const uint8_t png_prueba_tiles[3712];

#endif
