/*

 SELECTION_MENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : hud_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 96
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __selection_menu_h_INCLUDE
#define __selection_menu_h_INCLUDE

#define selection_menuWidth 20
#define selection_menuHeight 18
#define selection_menuBank 0

extern const unsigned char selection_menu[];

#endif

/* End of SELECTION_MENU.H */
