//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_titulo2_H
#define METASPRITE_titulo2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define titulo2_TILE_ORIGIN 0
#define titulo2_TILE_W 8
#define titulo2_TILE_H 8
#define titulo2_WIDTH 160
#define titulo2_HEIGHT 144
#define titulo2_TILE_COUNT 189
#define titulo2_PALETTE_COUNT 1
#define titulo2_COLORS_PER_PALETTE 4
#define titulo2_TOTAL_COLORS 4
#define titulo2_MAP_ATTRIBUTES 0
extern const unsigned char titulo2_map[360];
#define titulo2_map_attributes titulo2_map

BANKREF_EXTERN(titulo2)

extern const palette_color_t titulo2_palettes[4];
extern const uint8_t titulo2_tiles[3024];

#endif
