/*

 VICTORY_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\josem\Documents\Cuarto_Curso\TFG\github\proyecto_tfg\res\map_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __victory_screen_h_INCLUDE
#define __victory_screen_h_INCLUDE

#define victory_screenWidth 20
#define victory_screenHeight 18
#define victory_screenBank 0

extern const unsigned char victory_screen[];

#endif

/* End of VICTORY_SCREEN.H */
